### ISSUE TITLE
Update friendly_name

### ISSUE THREAD

**Issue by ekozan** [fonske/Brink-flair-modbus#14]
Hi, 

why we get back and Forth on This subject ? 

`#    name: "Temperature 3"`
`#    name: "${name} Temperature 3"`
`#    name: "Temperature 3"`

It's break ou automation every update :D 

Small edit : anyway thx for your work !!!!:

**Comment by fonske** [comment]
For home assistant its needed to use a friendly_name in the esphome code.
I have done this to keep al entities together when doing a search inside home assistant, so all entities will start with brink_xxx.

I apologize for breaking up the code.
