### ISSUE TITLE
Add level 0 settings

### ISSUE THREAD

**Issue by riesch** [fonske/Brink-flair-modbus#9]
Please add the following:

``

`
  - id: brink_flow_0
    name: Flow 0
    platform: modbus_controller
    modbus_controller_id: brink
    register_type: holding
    address: 6000
    unit_of_measurement: "m³/h"
    value_type: S_WORD      
    min_value: 0
    max_value: 400
    mode: slider
    icon: mdi:fan-auto
`

**Comment by fonske** [comment]
Done. Thank you.
